apiVersion: kubeadm.k8s.io/v1beta3
kind: ClusterConfiguration
kubernetesVersion: stable
controlPlaneEndpoint: "10.0.0.4:6443"
apiServer:
  certSANs:
    - "10.0.0.4"
networking:
  podSubnet: "10.244.0.0/16"
